import { env } from '$env/dynamic/private';

export const load = () => {
	return {
		SHOW_VERSION: env.SHOW_VERSION,
		ANALYTICS_UMAMI_CODE: env.ANALYTICS_UMAMI_CODE,
		ANALYTICS_UMAMI_SCRIPT: env.ANALYTICS_UMAMI_SCRIPT,
		ANALYTICS_PLAUSIBLE_CODE: env.ANALYTICS_PLAUSIBLE_CODE,
		ANALYTICS_PLAUSIBLE_SCRIPT: env.ANALYTICS_PLAUSIBLE_SCRIPT
	};
};
