services:
  timechart:
    image: besstiolle/timechart:latest
    container_name: timechart
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ${DB_LOCATION}:/app/db
    # Find out more about Timechart's environment variables here: https://github.com/besstiolle/Timeline/?tab=readm>
    environment:
      #ANALYTICS_UMAMI_CODE: ${TIMECHART_ANALYTICS_UMAMI_CODE}
      #ANALYTICS_UMAMI_SCRIPT: ${TIMECHART_ANALYTICS_UMAMI_SCRIPT}
      #ANALYTICS_PLAUSIBLE_CODE: ${TIMECHART_ANALYTICS_PLAUSIBLE_CODE}
      #ANALYTICS_PLAUSIBLE_SCRIPT: ${TIMECHART_ANALYTICS_PLAUSIBLE_SCRIPT}
      SHOW_VERSION: ${TIMECHART_SHOW_VERSION}
    env_file:
      - .env




