name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}
          CLEAN_TAG=$(echo "$RAW_TAG" | sed -E 's/^[^0-9]*//')
          echo "VERSION=$CLEAN_TAG" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          docker build --pull --rm -f Dockerfile -t ${{ secrets.DOCKERHUB_REPO }}:$VERSION .
          docker tag ${{ secrets.DOCKERHUB_REPO }}:$VERSION ${{ secrets.DOCKERHUB_REPO }}:latest

      - name: Push Docker image
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.DOCKERHUB_REPO }}:$VERSION
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest
